import { Poppins } from "next/font/google";
import "./globals.css";

const lato = Poppins({
  weight: ["100","200","500","300", "800","400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Concrete Inc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
