/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Wig7DYftaou
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function LandingPage() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <div className="flex items-center justify-center">Concrete Inc</div>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Services
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Projects
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-6 md:py-12 lg:py-16 xl:py-24">
          <div
            className="container flex flex-col items-center justify-center px-4 space-y-4 md:px-6">
            <div
              className="inline-block rounded-lg bg-gray-100 border border-gray-200 dark:bg-gray-800 dark:border-gray-800 dark:border-gray-800">
              <img
                alt="Hero"
                className="aspect-[4/1] object-cover object-top rounded-t-lg"
                height="225"
                src="/placeholder.svg"
                width="900" />
            </div>
            <div className="space-y-2 text-center">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Quality Concrete Services</h1>
              <p
                className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Your trusted partner for all your concrete needs. We deliver excellence.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Services</h2>
              <p
                className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We offer a wide range of concrete services to meet your construction needs.
              </p>
            </div>
            <div
              className="mx-auto grid max-w-5xl grid-cols-1 sm:grid-cols-2 gap-6 lg:gap-12">
              <div className="flex flex-col items-center gap-2">
                <TruckIcon className="w-24 h-24" />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Concrete Delivery</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    We deliver high-quality ready-mix concrete to your construction site.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <ConstructionIcon className="w-24 h-24" />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Concrete Mixing</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Our state-of-the-art mixing equipment ensures uniform and consistent concrete.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <ConstructionIcon className="w-24 h-24" />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Paving Services</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Let us handle your concrete paving projects, from sidewalks to driveways.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <ConstructionIcon className="w-24 h-24" />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Finishing Expertise</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Our skilled finishers can create the perfect surface texture for your concrete.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get a Free Quote</h2>
              <p
                className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Contact us today to discuss your project and get a free estimate.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="grid gap-4">
                <Input
                  className="border-gray-200 dark:border-gray-800"
                  placeholder="Name"
                  type="text" />
                <Input
                  className="border-gray-200 dark:border-gray-800"
                  placeholder="Email"
                  type="email" />
                <Input
                  className="border-gray-200 dark:border-gray-800"
                  placeholder="Phone"
                  type="tel" />
                <Textarea placeholder="Message" rows="3" />
                <Button type="submit">Submit</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Concrete Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}


function TruckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 18H3c-.6 0-1-.4-1-1V7c0-.6.4-1 1-1h10c.6 0 1 .4 1 1v11" />
      <path d="M14 9h4l4 4v4c0 .6-.4 1-1 1h-2" />
      <circle cx="7" cy="18" r="2" />
      <path d="M15 18H9" />
      <circle cx="17" cy="18" r="2" />
    </svg>)
  );
}


function ConstructionIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect x="2" y="6" width="20" height="8" rx="1" />
      <path d="M17 14v7" />
      <path d="M7 14v7" />
      <path d="M17 3v3" />
      <path d="M7 3v3" />
      <path d="M10 14 2.3 6.3" />
      <path d="m14 6 7.7 7.7" />
      <path d="m8 6 8 8" />
    </svg>)
  );
}
