"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RkPeY9pIPuo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function Testimonials() {
  return (
    <div className="w-full mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="relative overflow-hidden">
        <div className="flex space-x-6" style={{
          width: '200%',
          animation: 'scroll 30s linear infinite',
        }}>
          {/* First set of cards */}
          <TestimonialCard name="John Doe" role="CEO, Acme Inc." quote="Incredible service and products. Highly recommended!" />
          <TestimonialCard name="Jane Smith" role="Marketing Manager, XYZ Corp." quote="I've been using this product for years and it's a game-changer!" />
          <TestimonialCard name="Michael Johnson" role="Software Engineer, Globex Inc." quote="This is the best product I've ever used. Highly recommended!" />
          <TestimonialCard name="Emily Davis" role="Designer, Stark Industries" quote="I love this product! It has made my life so much easier." />
          <TestimonialCard name="Sarah Lee" role="Project Manager, Stark Industries" quote="This product has exceeded all my expectations. Highly recommended!" />
          <TestimonialCard name="David Kim" role="Sales Manager, Globex Inc." quote="This product has been a game-changer for my business. Highly recommended!" />

          {/* Duplicate set of cards */}
          <TestimonialCard name="John Doe" role="CEO, Acme Inc." quote="Incredible service and products. Highly recommended!" />
          <TestimonialCard name="Jane Smith" role="Marketing Manager, XYZ Corp." quote="I've been using this product for years and it's a game-changer!" />
          <TestimonialCard name="Michael Johnson" role="Software Engineer, Globex Inc." quote="This is the best product I've ever used. Highly recommended!" />
          <TestimonialCard name="Emily Davis" role="Designer, Stark Industries" quote="I love this product! It has made my life so much easier." />
          <TestimonialCard name="Sarah Lee" role="Project Manager, Stark Industries" quote="This product has exceeded all my expectations. Highly recommended!" />
          <TestimonialCard name="David Kim" role="Sales Manager, Globex Inc." quote="This product has been a game-changer for my business. Highly recommended!" />

          {/* Duplicate set of cards */}
          <TestimonialCard name="John Doe" role="CEO, Acme Inc." quote="Incredible service and products. Highly recommended!" />
          <TestimonialCard name="Jane Smith" role="Marketing Manager, XYZ Corp." quote="I've been using this product for years and it's a game-changer!" />
          <TestimonialCard name="Michael Johnson" role="Software Engineer, Globex Inc." quote="This is the best product I've ever used. Highly recommended!" />
          <TestimonialCard name="Emily Davis" role="Designer, Stark Industries" quote="I love this product! It has made my life so much easier." />
          <TestimonialCard name="Sarah Lee" role="Project Manager, Stark Industries" quote="This product has exceeded all my expectations. Highly recommended!" />
          <TestimonialCard name="David Kim" role="Sales Manager, Globex Inc." quote="This product has been a game-changer for my business. Highly recommended!" />
        </div>
      </div>
      <style jsx>{`
                @keyframes scroll {
                  0% {
                    transform: translateX(0);
                  }
                  100% {
                    transform: translateX(-50%);
                  }
                }
              `}</style>
    </div>
  );
}

function TestimonialCard({ name, role, quote }) {
  return (
    <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
      <Card className="h-full">
        <CardContent className="flex flex-col items-center justify-center p-6">
          <Avatar className="mb-4">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>{name[0]}</AvatarFallback>
          </Avatar>
          <h3 className="text-lg font-semibold mb-2">{name}</h3>
          <p className="text-muted-foreground text-sm mb-4">{role}</p>
          <p className="text-center text-wrap">&quot;{quote}&quot;</p>
        </CardContent>
      </Card>
    </div>
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
