/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RkPeY9pIPuo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function Testimonials() {
  return (
    (<div className="w-full mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="relative">
        <div className="overflow-hidden">
          <div className="flex animate-scroll-left space-x-6">
            <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
              <Card className="h-full">
                <CardContent className="flex flex-col items-center justify-center p-6">
                  <Avatar className="mb-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C1</AvatarFallback>
                  </Avatar>
                  <h3 className="text-lg font-semibold mb-2">John Doe</h3>
                  <p className="text-muted-foreground text-sm mb-4">CEO, Acme Inc.</p>
                  <p className="text-center">&quot;Incredible service and products. Highly recommended!&quot;</p>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
              <Card className="h-full">
                <CardContent className="flex flex-col items-center justify-center p-6">
                  <Avatar className="mb-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C2</AvatarFallback>
                  </Avatar>
                  <h3 className="text-lg font-semibold mb-2">Jane Smith</h3>
                  <p className="text-muted-foreground text-sm mb-4">Marketing Manager, XYZ Corp.</p>
                  <p className="text-center">
                    &quot;I&apos;ve been using this product for years and it&apos;s a game-changer!&quot;
                  </p>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
              <Card className="h-full">
                <CardContent className="flex flex-col items-center justify-center p-6">
                  <Avatar className="mb-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C3</AvatarFallback>
                  </Avatar>
                  <h3 className="text-lg font-semibold mb-2">Michael Johnson</h3>
                  <p className="text-muted-foreground text-sm mb-4">Software Engineer, Globex Inc.</p>
                  <p className="text-center">
                    &quot;This is the best product I&apos;ve ever used. Highly recommended!&quot;
                  </p>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
              <Card className="h-full">
                <CardContent className="flex flex-col items-center justify-center p-6">
                  <Avatar className="mb-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C4</AvatarFallback>
                  </Avatar>
                  <h3 className="text-lg font-semibold mb-2">Emily Davis</h3>
                  <p className="text-muted-foreground text-sm mb-4">Designer, Stark Industries</p>
                  <p className="text-center">&quot;I love this product! It has made my life so much easier.&quot;</p>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
              <Card className="h-full">
                <CardContent className="flex flex-col items-center justify-center p-6">
                  <Avatar className="mb-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C5</AvatarFallback>
                  </Avatar>
                  <h3 className="text-lg font-semibold mb-2">Sarah Lee</h3>
                  <p className="text-muted-foreground text-sm mb-4">Project Manager, Stark Industries</p>
                  <p className="text-center">
                    &quot;This product has exceeded all my expectations. Highly recommended!&quot;
                  </p>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-full sm:w-1/2 lg:w-1/3">
              <Card className="h-full">
                <CardContent className="flex flex-col items-center justify-center p-6">
                  <Avatar className="mb-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C6</AvatarFallback>
                  </Avatar>
                  <h3 className="text-lg font-semibold mb-2">David Kim</h3>
                  <p className="text-muted-foreground text-sm mb-4">Sales Manager, Globex Inc.</p>
                  <p className="text-center">
                    &quot;This product has been a game-changer for my business. Highly recommended!&quot;
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
        <div className="absolute top-1/2 -translate-y-1/2 left-4 z-10">
          <Button variant="ghost" size="icon">
            <ChevronLeftIcon className="w-6 h-6" />
            <span className="sr-only">Previous</span>
          </Button>
        </div>
        <div className="absolute top-1/2 -translate-y-1/2 right-4 z-10">
          <Button variant="ghost" size="icon">
            <ChevronRightIcon className="w-6 h-6" />
            <span className="sr-only">Next</span>
          </Button>
        </div>
      </div>
    </div>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
